# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Suman's blog
tagline:             'Random thoughts'
description:         ''
url:                 http://ramsuman.com
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Ram Suman Karumuri
  url:               https://twitter.com/mansu
  email:             suman.karumuri@gmail.com

# Custom vars
version:             1.0.0
